// Shared, mutable application state for the tracker page. app.js and the
// feature modules it composes all import this single object by reference, so
// every module reads and writes the same live state.
export const state = {
  data: [],
  universities: [],
  programs: [],
  programmeGroups: [],
  applicantCategoryLabels: {},
  policies: [],
  coverage: null,
  sourceMonitor: {},
  rankingPayload: { rankings: {} },
  universityById: new Map(),
  ranking: "qs",
  officialCount: 0,
  predictionCount: 0,
  meta: {},
  search: "",
  region: "all",
  intake: "all",
  status: "open",
  sort: "rank",
  rankLimit: "200",
  favorites: new Set(),
  favoritesOnly: false,
  language: "en",
  theme: "light",
  monitorPayload: null,
  optionalFailureCount: 0,
  pages: {},
  expandedWindowGroups: new Set(),
  expandedUniversityGroups: new Set(),
  activeReviewUniversity: null,
  authToken: "",
  user: null,
  favoriteSyncTimer: null,
};
